/* Isola — Alameda Eats · data & config.
   PHOTO POLICY: img:"" renders the branded monogram tile (honest default).
   Only set img to a REAL photo of that restaurant, provided by the owner
   or licensed — never stock photos or images lifted from Yelp/Google.
   CONFIG: flip monetization switches here (contact email, AdSense id, Formspree id).
   RESTAURANTS: drives the app AND build-pages.js (run `node build-pages.js` after edits).
   To sell a Featured placement: set featured:true on that restaurant. */
/* ===========================================================
   CONFIG — edit these to turn on revenue features
   =========================================================== */
const CONFIG = {
  CANONICAL: "https://stevenslegacystudios.github.io/Golden-State-Ryders-Gemma-4/",
  CONTACT_EMAIL: "StevensLegacyStudios@gmail.com", // where "Get Featured" + contact go
  ADSENSE_CLIENT: "",   // e.g. "ca-pub-1234567890123456" — leave "" until AdSense-approved
  FORMSPREE_ID:   ""    // e.g. "xayzwvut" — newsletter capture endpoint (formspree.io/f/<id>)
};

/* ===========================================================
   RESTAURANT DATA
   hours: index 0=Sun..6=Sat. Each day = array of [open,close] in 24h decimal (17.5=5:30pm). [] = closed.
   cuisine: primary cuisine (drives cuisine filters).  cats: feature flags (waterfront/patio/breakfast/vegan/delivery).
   featured: true => pinned to top with a "Featured" badge (paid placement).
   =========================================================== */
const RESTAURANTS = [
  { name:"Trabocco Kitchen & Cocktails", emoji:"🍤", cuisine:"Italian", featured:false,
    img:"",
    rating:"4.5", price:"$$$", tags:["Pasta","Seafood","Cocktails","Patio"], cats:["patio"],
    desc:"Chef-owner Giuseppe Naccarelli's seasonal Abruzzo-inspired cooking with a sleek bar and year-round outdoor dining at South Shore.",
    address:"2213 South Shore Center, Alameda, CA 94501", phone:"+15105211152", phoneLabel:"(510) 521-1152",
    website:"https://trabocco.com", menuUrl:"https://trabocco.com/menu/", reserve:"https://www.opentable.com/r/trabocco-alameda",
    hours:[[[11.5,21]],[],[[11.5,21]],[[11.5,21]],[[11.5,21]],[[11.5,22]],[[11.5,22]]],
    menu:[
      {sec:"Antipasti",items:[{n:"Burrata & Prosciutto",d:"Creamy burrata, San Daniele prosciutto, grilled bread",p:"$18"},{n:"Calamari Fritti",d:"Crispy calamari, spicy arrabbiata aioli",p:"$17"}]},
      {sec:"Pasta",items:[{n:"Pappardelle al Ragù di Agnello",d:"House pappardelle, slow-braised lamb ragù",p:"$28"},{n:"Risotto ai Frutti di Mare",d:"Seafood risotto with clams, mussels & shrimp",p:"$30"}]},
      {sec:"Secondi",items:[{n:"Pollo alla Contadina",d:"Wood-fired half chicken, rosemary potatoes",p:"$29"},{n:"Seafood Platter",d:"Wood-fired catch of the day, market veg",p:"$42"}]},
      {sec:"Dolci",items:[{n:"Tiramisù",d:"The house classic — guest favorite",p:"$12"}]}
    ]},
  { name:"The Star on Park", emoji:"🍕", cuisine:"Italian", featured:false,
    img:"",
    rating:"4.4", price:"$$", tags:["Deep-Dish","Pizza","Craft Cocktails","Bar"], cats:[],
    desc:"Downtown's artisan pizzeria & cocktail bar — Chicago-style deep dish and thin crust with a serious full bar.",
    address:"1400 Park St, Alameda, CA 94501", phone:"+15108327827", phoneLabel:"(510) 832-7827",
    website:"https://thestaronpark.com", menuUrl:"https://thestaronpark.com/menu/", reserve:"https://www.opentable.com/r/the-star-on-park-alameda",
    hours:[[[11.5,21]],[[11.5,21]],[[11.5,21]],[[11.5,21]],[[11.5,21]],[[11.5,22]],[[11.5,22]]],
    menu:[
      {sec:"Starters",items:[{n:"Wedge Salad",d:"Iceberg, blue cheese, bacon, buttermilk ranch",p:"$13"},{n:"Garlic Knots",d:"House dough, garlic butter, marinara",p:"$9"}]},
      {sec:"Deep Dish",items:[{n:"Classic Cheese",d:"Chicago-style, two-cheese blend, chunky tomato",p:"$24"},{n:"The Works",d:"Sausage, pepperoni, peppers, onion, mushroom",p:"$29"}]},
      {sec:"Thin Crust",items:[{n:"Margherita",d:"Fresh mozzarella, basil, San Marzano",p:"$19"},{n:"Hot Honey Pepperoni",d:"Pepperoni cups, mozzarella, chili honey",p:"$22"}]}
    ]},
  { name:"Tomatina", emoji:"🍝", cuisine:"Italian", featured:false,
    img:"",
    rating:"4.1", price:"$$", tags:["Pasta","Pizza","Piadine","Family"], cats:[],
    desc:"Relaxed Park Street neighborhood Italian — hearty unpretentious pasta, pizza and piadine. Great for families and groups.",
    address:"1338 Park St, Alameda, CA 94501", phone:"+15105211000", phoneLabel:"(510) 521-1000",
    website:"https://tomatina.com/menu/tomatina-alameda-1338-park-street", menuUrl:"https://tomatina.com/menu/tomatina-alameda-1338-park-street", reserve:"https://www.opentable.com/r/tomatina-alameda",
    hours:[[[11,21]],[[11,21]],[[11,21]],[[11,21]],[[11,21]],[[11,22]],[[11,22]]],
    menu:[
      {sec:"Salads",items:[{n:"Mixta",d:"Greens, gorgonzola, pickled onion, candied walnuts, honey-mustard",p:"$13"},{n:"Caesar",d:"Romaine, parmesan, garlic croutons",p:"$11"}]},
      {sec:"Pasta",items:[{n:"Spaghetti & Meatballs",d:"House marinara, beef-pork meatballs",p:"$18"},{n:"Penne al Pesto",d:"Basil pesto, pine nuts, parmesan",p:"$16"}]},
      {sec:"Piadine & Pizza",items:[{n:"Margherita Pizza",d:"Mozzarella, tomato, basil",p:"$16"},{n:"Chicken Piadina",d:"Italian flatbread, grilled chicken, greens",p:"$15"}]}
    ]},
  { name:"Pasta Pelican", emoji:"🌊", cuisine:"Italian", featured:false,
    img:"",
    rating:"4.3", price:"$$", tags:["Waterfront","Pasta","Seafood","Wine"], cats:["waterfront"],
    desc:"Classic waterfront dining on the Oakland Estuary — traditional Italian & Americana with marina views and a big wine list.",
    address:"2455 Mariner Square Dr, Alameda, CA 94501", phone:"+15108647427", phoneLabel:"(510) 864-7427",
    website:"https://www.pastapelican.com", menuUrl:"https://www.pastapelican.com/menu/", reserve:"https://www.pastapelican.com/reservations/",
    hours:[[[11.5,21]],[[11.5,14.5],[16.5,21]],[[11.5,14.5],[16.5,21]],[[11.5,14.5],[16.5,21]],[[11.5,14.5],[16.5,21]],[[11.5,21]],[[11.5,21]]],
    menu:[
      {sec:"Antipasti",items:[{n:"Steamed Clams",d:"White wine, garlic, herbs, grilled bread",p:"$17"},{n:"Caprese",d:"Tomato, fresh mozzarella, basil, balsamic",p:"$14"}]},
      {sec:"Pasta",items:[{n:"Linguine alle Vongole",d:"Fresh clams, garlic, white wine",p:"$24"},{n:"Fettuccine Alfredo",d:"Parmesan cream, add chicken or prawns",p:"$21"}]},
      {sec:"From the Sea",items:[{n:"Cioppino",d:"San Francisco seafood stew, tomato broth",p:"$32"},{n:"Grilled Salmon",d:"Seasonal vegetables, lemon butter",p:"$28"}]}
    ]},
  { name:"Pizzeria Pappo", emoji:"🍕", cuisine:"Italian", featured:false,
    img:"",
    rating:"4.4", price:"$$", tags:["Wood-Fired","Pizza","Antipasti","Cozy"], cats:[],
    desc:"Crispy thin-crust wood-fired pizza on Santa Clara Ave with sharp seasonal salads and a fun soft-serve finish.",
    address:"709 Santa Clara Ave, Alameda, CA 94501", phone:"+15104730613", phoneLabel:"(510) 473-0613",
    website:"https://pizzeriapappo.com", menuUrl:"https://pizzeriapappo.com/order", reserve:"https://pizzeriapappo.com/contact-us",
    hours:[[],[],[[11.5,14.5],[17,20.5]],[[11.5,14.5],[17,20.5]],[[11.5,14.5],[17,20.5]],[[11.5,14.5],[17,20.5]],[[11.5,14.5],[17,20.5]]],
    menu:[
      {sec:"To Start",items:[{n:"Golden Beet Salad",d:"Roasted beets, citrus, goat cheese, pistachio",p:"$14"},{n:"Wings",d:"Crispy wings, dill pickle ranch",p:"$13"}]},
      {sec:"Wood-Fired Pizza",items:[{n:"Margherita",d:"San Marzano, fresh mozzarella, basil",p:"$18"},{n:"Sausage & Fennel",d:"House sausage, fennel, chili, mozzarella",p:"$21"}]},
      {sec:"Sweet",items:[{n:"Soft Serve",d:"Vanilla, olive oil & flaky salt",p:"$7"}]}
    ]},
  { name:"East End", emoji:"🍕", cuisine:"Italian", featured:false,
    img:"",
    rating:"4.4", price:"$$", tags:["Wood-Fired","Oysters","Cocktails","Date Night"], cats:[],
    desc:"Park Street favorite slinging native-yeast sourdough wood-fired pizzas since 2011, plus shucked-to-order oysters, craft cocktails and seasonal small plates. Lively, dinner-only.",
    address:"1650 Park St, Unit A, Alameda, CA 94501", phone:"+15102639630", phoneLabel:"(510) 263-9630",
    website:"https://www.eastendalameda.com", menuUrl:"https://www.eastendalameda.com/food", reserve:"https://www.eastendalameda.com/make-a-reservation-at-east-end",
    hours:[[],[],[[17,21]],[[17,21]],[[17,21]],[[17,21.5]],[[17,21]]],
    menu:[
      {sec:"Wood-Fired Pizza",items:[{n:"Margherita",d:"Red sauce, hand-pulled mozzarella, fresh basil",p:"$18"},{n:"Diablita",d:"Red sauce, Calabrian chiles, house cheese, goat cheese, shaved garlic",p:"$18"},{n:"Caruso",d:"Béchamel, fire-roasted leeks, sottocenere",p:"$18"}]},
      {sec:"To Share",items:[{n:"Wings",d:"Mary's wings, Calabrian glaze, roasted garlic buttermilk",p:"$15"},{n:"Garlic Toast",d:"Fried garlic-drenched sourdough, parm, herbs",p:"$9"},{n:"Arugula Salad",d:"Fava beans, shaved fennel, preserved lemon, pecorino",p:"$13"},{n:"Kennebec Fries",d:"Hand-cut, tomato jam & Calabrian aiolis",p:"$10"}]}
    ]},
  { name:"C'era Una Volta", emoji:"🍝", cuisine:"Italian", featured:false,
    img:"",
    rating:"4.1", price:"$$", tags:["Tuscan","Handmade Pasta","Wine List","Vegan Options"], cats:["vegan"],
    desc:"Authentic Tuscan kitchen from a Florentine-trained chef — handmade pastas, risottos and a deep Italian wine list. A longtime island favorite for lunch and early dinner.",
    address:"800 W Tower Ave, Alameda, CA 94501", phone:"+15107694828", phoneLabel:"(510) 769-4828",
    website:"https://www.ceraunavolta.us", menuUrl:"https://www.ceraunavolta.us/chefs-specials-menu", reserve:"https://www.ceraunavolta.us",
    hours:[[],[[11,16]],[[11,18]],[[11,18]],[[11,18]],[[11,18]],[[11,14]]],
    menu:[
      {sec:"Antipasti",items:[{n:"Piatto Freddo Misto",d:"Prosciutto, coppa, salame, olives, cheese, cured veg",p:"$18"},{n:"Insalata Ave Cesare",d:"Romaine, anchovies, Parmigiano, crostini",p:"$11"},{n:"Insalata Barbabietole",d:"Roasted beets, greens, pistachios, balsamic",p:"$11"}]},
      {sec:"Pasta & Risotto",items:[{n:"Gnocchi ai Tartufo",d:"Truffle gnocchi, porcini cream, Parmigiano",p:"$20"},{n:"Ravioli ai Carciofi",d:"Artichoke ravioli, cream & walnut sauce",p:"$19"},{n:"Tagliolini con Branzino",d:"Egg pasta, lightly spicy tomato, branzino",p:"$21"},{n:"Risotto ai Funghi",d:"Creamy mushroom risotto",p:"$18"}]}
    ]},
  { name:"The Park Street Tavern", emoji:"🍷", cuisine:"Italian", featured:false,
    img:"",
    rating:"4.7", price:"$$$", tags:["Italian-Mediterranean","Pasta","Cocktails","Date Night"], cats:[],
    desc:"A warm, quaint Park Street dining room serving Greek- and Italian-influenced Mediterranean plates with house pasta, scaloppini and steaks. Known for its cocktail program.",
    address:"1901 Park St, Alameda, CA 94501", phone:"+15106712867", phoneLabel:"(510) 671-2867",
    website:"https://theparkstreettavern.com", menuUrl:"https://theparkstreettavern.com/alameda-the-park-street-tavern-food-menu", reserve:"https://www.opentable.com/r/the-park-street-tavern-reservations-alameda",
    hours:[[[16,21]],[[17,21]],[[17,21]],[[17,21]],[[17,21]],[[17,21]],[[17,21]]],
    menu:[
      {sec:"Starters",items:[{n:"Spanakopita",d:"Flaky phyllo, spinach & feta",p:"$14"},{n:"Halloumi",d:"Grilled Mediterranean cheese",p:"$15"},{n:"Sautéed Prawns",d:"Shareable, Mediterranean-style",p:"$18"}]},
      {sec:"Pasta & Mains",items:[{n:"Capellini Scampi",d:"Angel hair, shrimp, garlic white-wine scampi",p:"$35"},{n:"Chicken Scaloppini Piccata",d:"Lemon-caper butter, house noodles",p:"$33"},{n:"Veal Scaloppini",d:"Thin veal cutlets, classic preparation",p:"$38"},{n:"14oz Ribeye",d:"Grilled ribeye with sides",p:"$59"}]}
    ]},
  { name:"Santoro's Italian Market & Deli", emoji:"🥪", cuisine:"Italian", featured:false,
    img:"",
    rating:"4.6", price:"$$", tags:["Italian Deli","Sandwiches","Boar's Head","Casual"], cats:[],
    desc:"West End Italian market and deli famous for huge handmade sandwiches on fresh Semifreddi's bread, plus daily specials like lasagna and chicken parm and imported groceries.",
    address:"475 Santa Clara Ave, Alameda, CA 94501", phone:"+15102178710", phoneLabel:"(510) 217-8710",
    website:"https://www.santorosalameda.com", menuUrl:"https://www.santorosalameda.com", reserve:"https://www.santorosalameda.com",
    hours:[[],[[10.5,15]],[[10.5,15]],[[10.5,15]],[[10.5,15]],[[10.5,15]],[[11,15]]],
    menu:[
      {sec:"Sandwiches",items:[{n:"Italian Combo",d:"Capicola, salami, mortadella, provolone & veg",p:"$17.50"},{n:"Meatball",d:"House meatballs in red sauce (Friday special)",p:"$15"},{n:"Chicken Parm",d:"Breaded chicken, marinara, melted cheese",p:"$15"}]},
      {sec:"From the Deli Case",items:[{n:"Lasagna",d:"Layered pasta with meat & cheese (daily special)",p:"$14"},{n:"Pasta Salad",d:"House-made deli-case pasta salad",p:"$6"},{n:"Marinated Mushrooms & Artichokes",d:"Imported Italian antipasti",p:"$8"},{n:"Pizza Slice",d:"House Italian-style pizza by the slice",p:"$5"}]}
    ]},
  { name:"Alameda Pizza", emoji:"🍕", cuisine:"Italian", featured:false,
    img:"",
    rating:"4.0", price:"$$", tags:["Casual","Deep Dish","Calzones","Family"], cats:["delivery"],
    desc:"A casual, seat-yourself Webster Street pizzeria serving hand-made thin and deep-dish pies, calzones, lasagna and made-to-order pasta. A longtime West End spot for dine-in or takeout.",
    address:"1538 Webster St, Alameda, CA 94501", phone:"+15105237149", phoneLabel:"(510) 523-7149",
    website:"https://alamedapizza.gotoeat.net", menuUrl:"https://alamedapizza.gotoeat.net/menu", reserve:"https://order.online/store/alameda-pizza-alameda-526075/",
    hours:[[[12,20]],[[11,21]],[[11,21]],[[11,21]],[[11,21]],[[11,21]],[[11,21]]],
    menu:[
      {sec:"Pizza & Calzones",items:[{n:"Vegetarian Pizza",d:"Mushrooms, peppers, tomatoes, onions, olives",p:"$24"},{n:"BBQ Chicken Pizza",d:"BBQ sauce, chicken, red & green onions",p:"$23.50"},{n:"Calzone",d:"Ricotta, mozzarella, tomato sauce, custom fillings",p:"$15"}]},
      {sec:"Pasta",items:[{n:"Ravioli",d:"Cheese ravioli, marinara or meat sauce",p:"$17.50"},{n:"Baked Ziti",d:"Baked pasta, tomato sauce, melted cheese",p:"$16"},{n:"Shrimp Scampi",d:"Pasta, shrimp, garlic butter scampi",p:"$18"},{n:"Lasagna",d:"Layered baked pasta, meat sauce & cheese",p:"$17"}]}
    ]},
  { name:"La Penca Azul", emoji:"🌮", cuisine:"Mexican", featured:false,
    img:"",
    rating:"4.3", price:"$$", tags:["Tacos","Burritos","Tequila Bar","Family-Owned"], cats:["delivery"],
    desc:"Long-running Park Street favorite serving authentic, made-to-order Mexican classics, fresh seafood, and 100% blue agave tequilas. Known for huge super burritos, street tacos, and house mole.",
    address:"1440 Park St, Alameda, CA 94501", phone:"+15107699110", phoneLabel:"(510) 769-9110",
    website:"https://lapencaazul.com/lapencaazulparkst", menuUrl:"https://lapencaazul.com/lapencaazulparkst", reserve:"https://www.grubhub.com/restaurant/la-penca-azul-1440-park-st-alameda/719198",
    hours:[[[9,24]],[[9,22]],[[9,22]],[[9,22]],[[9,22]],[[9,24]],[[9,24]]],
    menu:[
      {sec:"Antojitos & Tacos",items:[{n:"Street Tacos",d:"Soft corn tortillas, choice of meat, onion, cilantro & salsa",p:"$13"},{n:"Fish Tacos",d:"Grilled or battered fish, cabbage, chipotle crema",p:"$15"},{n:"Super Famoso Burrito",d:"Oversized burrito with rice, beans, cheese & protein",p:"$16"}]},
      {sec:"Especialidades",items:[{n:"Chicken Mole Enchiladas",d:"Enchiladas in rich house-made mole poblano",p:"$18"},{n:"Shrimp Fajitas",d:"Sizzling prawns, peppers, onions, rice & beans",p:"$22"},{n:"Camarones al Mojo",d:"Prawns sautéed in garlic butter sauce",p:"$20"},{n:"Caldo de Camarón",d:"Shrimp soup with vegetables in savory broth",p:"$18"}]}
    ]},
  { name:"Toomie's by Thai Golden Rice", emoji:"🍜", cuisine:"Thai", featured:false,
    img:"",
    rating:"4.2", price:"$$", tags:["Thai","Curry","Noodles","Family-Owned"], cats:["delivery"],
    desc:"A longtime family-owned Alameda favorite on Park Street serving authentic Thai curries, noodles, and classics. Previously voted #1 Restaurant in Alameda by Alameda Magazine.",
    address:"1433 Park St, Alameda, CA 94501", phone:"+15108658008", phoneLabel:"(510) 865-8008",
    website:"https://www.toomiesthai.com/", menuUrl:"https://www.toomiesthai.com/", reserve:"https://www.opentable.com/r/toomies-thai-cuisine-alameda",
    hours:[[[11,21.5]],[[11,21.5]],[[11,21.5]],[[11,21.5]],[[11,21.5]],[[11,21.5]],[[11,21.5]]],
    menu:[
      {sec:"Appetizers & Soups",items:[{n:"Spring Rolls",d:"Deep-fried rolls, chicken & shrimp, plum sauce",p:"$10"},{n:"Chicken Satay",d:"Grilled skewers, yellow curry & coconut, peanut sauce",p:"$12"},{n:"Tom Yum",d:"Hot & sour soup, lemongrass, galangal, Thai herbs",p:"$10"}]},
      {sec:"Curries & Noodles",items:[{n:"Green Curry",d:"Coconut milk, eggplant, bell pepper, Thai basil",p:"$15"},{n:"Panang Curry",d:"Coconut milk, bell pepper, kaffir lime leaves",p:"$15"},{n:"Pad Thai",d:"Rice noodles, egg, bean sprouts, tofu, peanuts",p:"$14"},{n:"Pad See Ew",d:"Wide rice noodles, egg, Chinese broccoli, sweet soy",p:"$14"}]}
    ]},
  { name:"East Ocean Seafood Restaurant", emoji:"🥟", cuisine:"Chinese", featured:false,
    img:"",
    rating:"4.1", price:"$$", tags:["Dim Sum","Cantonese","Seafood","Hong Kong Style"], cats:["delivery"],
    desc:"Long-running Alameda dim sum house on Webster Street serving fresh, cart-pushed dim sum by day and live-seafood, Hong Kong-style banquet dishes by night.",
    address:"1713 Webster St, Alameda, CA 94501", phone:"+15108653381", phoneLabel:"(510) 865-3381",
    website:"https://east-ocean-seafood.res-menu.net/", menuUrl:"https://east-ocean-seafood.res-menu.net/", reserve:"https://www.opentable.com/r/east-ocean-seafood-restaurant-alameda",
    hours:[[[10,14.5],[17,21]],[[11,14.5],[17,20]],[[11,14.5],[17,20]],[[11,14.5],[17,20]],[[11,14.5],[17,20]],[[11,14.5],[17,20]],[[10,14.5],[17,21.5]]],
    menu:[
      {sec:"Dim Sum",items:[{n:"Shrimp Har Gow",d:"Steamed crystal-skin dumplings with whole shrimp",p:"$9.95"},{n:"Pork & Shrimp Siu Mai",d:"Open-topped steamed pork & shrimp dumplings",p:"$9.95"},{n:"BBQ Pork Buns",d:"Fluffy buns with sweet roast pork",p:"$9.95"},{n:"Egg Custard Tarts",d:"Flaky tartlets with silky egg custard",p:"$9.95"}]},
      {sec:"Seafood & House Specialties",items:[{n:"Salt & Pepper Calamari",d:"Crispy fried squid, salt, pepper, chili",p:"$16.95"},{n:"Seared Scallops with Mushrooms",d:"Fresh scallops, mixed mushrooms, light sauce",p:"$22.95"},{n:"Beef Dry Chow Fun",d:"Wok-fried wide rice noodles, beef, bean sprouts",p:"$22.95"}]}
    ]},
  { name:"Pho Anh Dao Alameda", emoji:"🍲", cuisine:"Vietnamese", featured:false,
    img:"",
    rating:"4.4", price:"$$", tags:["Pho","Banh Mi","Noodle Soup","Casual"], cats:["delivery"],
    desc:"Friendly, affordable Webster Street Vietnamese spot known for richly flavored pho, banh mi, and generous portions at great value. A reliable neighborhood favorite for consistent comfort food.",
    address:"1919 Webster St, Alameda, CA 94501", phone:"+15102638577", phoneLabel:"(510) 263-8577",
    website:"https://phoanhdao.com/", menuUrl:"https://phoanhdao.com/", reserve:"https://www.ubereats.com/store/pho-anh-dao-alameda/36soSRIdTdm1EE19kDXxMQ",
    hours:[[[11,21]],[],[[11,21]],[[11,21]],[[11,21]],[[11,21]],[[11,21]]],
    menu:[
      {sec:"Pho & Soups",items:[{n:"Pho Dac Biet",d:"House special pho: steak, flank, brisket, tendon & tripe",p:"$15.50"},{n:"Pho Ga",d:"Chicken pho in clear aromatic broth",p:"$15.50"},{n:"Pho Tai",d:"Pho with thinly sliced rare steak",p:"$15"}]},
      {sec:"Appetizers & Rice Plates",items:[{n:"Shrimp & Pork Spring Rolls",d:"Fresh rolls, herbs, peanut sauce (2)",p:"$4.50"},{n:"Basil Wings",d:"Crispy fried wings tossed in Thai basil (4)",p:"$6.50"},{n:"Banh Mi",d:"Pickled veg, cilantro, choice of protein",p:"$8"},{n:"Vermicelli Bowl",d:"Rice noodles, grilled meat, herbs, nuoc cham",p:"$14"}]}
    ]},
  { name:"Angel Fish Japanese Restaurant", emoji:"🍣", cuisine:"Japanese", featured:false,
    img:"",
    rating:"4.2", price:"$$", tags:["Sushi","Sashimi","Tempura","Bay Views"], cats:["delivery","waterfront"],
    desc:"A well-loved neighborhood Japanese sushi spot on Alameda's Bay Farm Island, serving fresh sashimi, signature rolls, tempura, and warm kitchen dishes like teriyaki and udon.",
    address:"883 Island Dr, Ste C-2, Alameda, CA 94502", phone:"+15107490460", phoneLabel:"(510) 749-0460",
    website:"https://www.angelfishalameda.com/", menuUrl:"https://www.angelfishalameda.com/menu/", reserve:"https://order.online/store/angel-fish-japanese-restaurant-alameda-46266",
    hours:[[[16,20]],[],[[11.5,14],[16,21]],[[11.5,14],[16,21]],[[11.5,14],[16,21]],[[11.5,14],[16,21]],[[15,21]]],
    menu:[
      {sec:"Sushi & Sashimi",items:[{n:"Chirashi",d:"Assorted sashimi over seasoned sushi rice",p:"$24"},{n:"Sashimi Combination",d:"Chef's-choice sashimi, fresh and properly cut",p:"$26"},{n:"California Roll",d:"Real crab, avocado, cucumber",p:"$9"},{n:"Spicy Tuna Roll",d:"Fresh tuna with spicy sauce",p:"$9"}]},
      {sec:"Kitchen",items:[{n:"Tempura Udon",d:"Thick noodles in hot broth, shrimp & veg tempura",p:"$16"},{n:"Beef Teriyaki",d:"Grilled rib eye, house teriyaki",p:"$22"},{n:"Tempura Combination",d:"Crispy shrimp & assorted vegetable tempura",p:"$17"}]}
    ]},
  { name:"India Palace", emoji:"🍛", cuisine:"Indian", featured:false,
    img:"",
    rating:"4.3", price:"$$", tags:["Indian","Lunch Buffet","Curry","Tandoori"], cats:["delivery","vegan"],
    desc:"Longtime Alameda favorite serving authentic North Indian cuisine, best known for its lunch buffet and rich curries, tandoori dishes, and many vegetarian, vegan, and gluten-free options.",
    address:"737 Buena Vista Ave, Alameda, CA 94501", phone:"+15108148778", phoneLabel:"(510) 814-8778",
    website:"https://www.alamedaindiapalace.com/", menuUrl:"https://www.alamedaindiapalace.com/menu", reserve:"https://www.alamedaindiapalace.com/",
    hours:[[[17,21.5]],[[11,14],[17,21.5]],[[11,14],[17,21.5]],[[11,14],[17,21.5]],[[11,14],[17,21.5]],[[11,14],[17,21.5]],[[11,14],[17,21.5]]],
    menu:[
      {sec:"Tandoori & Appetizers",items:[{n:"Tandoori Chicken",d:"Yogurt-and-spice marinated chicken from the clay tandoor",p:"$20"},{n:"Paneer Tikka",d:"Homemade cheese, ginger, garlic, Indian spices",p:"$18"},{n:"Vegetable Samosa",d:"Crispy pastry, spiced potatoes & peas",p:"$6"}]},
      {sec:"Curries & Entrees",items:[{n:"Chicken Tikka Masala",d:"Tandoor chicken in rich cream & cashew sauce",p:"$17"},{n:"Chicken Saag",d:"Chicken cooked with spiced cream and spinach",p:"$17"},{n:"Lamb Curry",d:"Classic lamb simmered in spiced curry",p:"$17"},{n:"Garlic Naan",d:"Leavened tandoor bread with fresh garlic",p:"$4"}]}
    ]},
  { name:"Spinning Bones", emoji:"🍗", cuisine:"American", featured:false,
    img:"",
    rating:"4.4", price:"$$", tags:["Rotisserie","Roasted Meats","Casual","Michelin Bib Gourmand"], cats:["patio"],
    desc:"A MICHELIN Bib Gourmand California rotisserie on Park Street specializing in slow-roasted koji chicken, peppered beef and barbecue pork ribs with bold global flavors. Easygoing and shareable.",
    address:"1205 Park St, Alameda, CA 94501", phone:"+15102639290", phoneLabel:"(510) 263-9290",
    website:"https://www.spinningbones.com/", menuUrl:"https://www.spinningbones.com/menus", reserve:"https://www.opentable.com/r/spinning-bones-alameda",
    hours:[[[11.5,20]],[],[],[[11.5,20]],[[11.5,20]],[[11.5,21]],[[11.5,21]]],
    menu:[
      {sec:"Starters",items:[{n:"Goodie Sampler",d:"Vegan cashew cheese, baba ganoush, falafel, veggies, roti",p:"$16"},{n:"Chicken Lickin'",d:"Mochiko fried chicken nuggets, ginger, soy, tofu aioli",p:"$12"},{n:"Korroke",d:"Panko sweet potato croquettes, cheddar, tonkatsu",p:"$9"},{n:"Paté",d:"Chicken liver mousse, fig jam, pickles, crostini",p:"$14"}]},
      {sec:"From the Spit",items:[{n:"Koji Chicken",d:"Half koji-brined rotisserie chicken, sides & roti",p:"$35"},{n:"St. Louis Ribs",d:"SB BBQ, yellow curry salt, napa slaw, pickled jalapeños",p:"$24"},{n:"Black Pepper Beef",d:"Peppered slow-roasted beef, sides, chimichurri",p:"$35"},{n:"Trip's Triple",d:"Trio of rotisserie meats for sharing with sides",p:"$46"}]}
    ]},
  { name:"Pier 29 Waterfront Restaurant & Bar", emoji:"🦞", cuisine:"Seafood", featured:false,
    img:"",
    rating:"4.3", price:"$$", tags:["Waterfront","Seafood","Steakhouse","Bay Views"], cats:["waterfront","patio"],
    desc:"A longtime waterfront seafood-and-steakhouse on Ballena Bay where every table has a San Francisco Bay view and parking is free. Known for famous clam chowder, fresh oysters, fish & chips and prime rib.",
    address:"1148 Ballena Blvd, Alameda, CA 94501", phone:"+15108655088", phoneLabel:"(510) 865-5088",
    website:"https://pier29alameda.com/", menuUrl:"https://pier29alameda.com/menu/", reserve:"https://www.opentable.com/r/pier-29-waterfront-restaurant",
    hours:[[[10.5,21]],[],[[10.5,21]],[[10.5,21]],[[10.5,21]],[[10.5,21]],[[10.5,21]]],
    menu:[
      {sec:"Starters",items:[{n:"Famous Clam Chowder",d:"House signature New England clam chowder",p:"$9"},{n:"Calamari",d:"Lightly fried calamari with dipping sauce",p:"$15"},{n:"Crab Cakes",d:"Pan-seared crab cakes with remoulade",p:"$17"},{n:"Fresh Oysters",d:"Half-dozen oysters on the half shell",p:"$18"}]},
      {sec:"Mains",items:[{n:"Fish & Chips",d:"Beer-battered cod, fries, tartar",p:"$20"},{n:"Lamb Shank",d:"Slow-braised lamb shank with vegetables",p:"$28"},{n:"Angus Prime Rib",d:"Slow-roasted Angus prime rib with au jus",p:"$34"}]}
    ]},
  { name:"Ole's Waffle Shop", emoji:"🧇", cuisine:"American", featured:false,
    img:"",
    rating:"4.5", price:"$$", tags:["Diner","Breakfast","Waffles","Historic"], cats:["breakfast"],
    desc:"A beloved Park Street diner serving the East Bay since 1927, famous for crispy golden waffles, generous pancake platters and fresh-squeezed orange juice. Classic comfort breakfast and lunch, 7 days a week.",
    address:"1507 Park St, Alameda, CA 94501", phone:"+15105228108", phoneLabel:"(510) 522-8108",
    website:"https://www.oleswaffleshop.com/", menuUrl:"https://www.oleswaffleshop.com/", reserve:"https://www.oleswaffleshop.com/",
    hours:[[[6,20.5]],[[6,20.5]],[[6,20.5]],[[6,20.5]],[[6,20.5]],[[6,20.5]],[[6,20.5]]],
    menu:[
      {sec:"Breakfast",items:[{n:"Belgian Waffle",d:"Signature crispy golden waffle",p:"$8"},{n:"Pancakes or Waffle + Two Eggs",d:"Griddle classic with two large eggs",p:"$8.95"},{n:"Waffle with Bacon",d:"Waffle plus four slices of crispy bacon",p:"$9.75"},{n:"Corned Beef Hash & Eggs",d:"House corned beef hash, eggs any style",p:"$13"},{n:"Omelet, Hash Browns & Toast",d:"Made-to-order omelet, crispy hash browns",p:"$13"}]},
      {sec:"Drinks",items:[{n:"Fresh-Squeezed Orange Juice",d:"Squeezed to order in front of you",p:"$5"}]}
    ]},
  { name:"Crispian Bakery", emoji:"🥐", cuisine:"Cafe", featured:false,
    img:"",
    rating:"4.7", price:"$$", tags:["Bakery","Pastries","Coffee","French-American"], cats:["breakfast"],
    desc:"An artisan French-American bakery on Park Street turning out flaky all-butter croissants, kouign amann, naturally fermented breads, macarons and quiches, plus coffee. A neighborhood favorite for morning pastries.",
    address:"1700 Park St, Ste 120, Alameda, CA 94501", phone:"+15102394751", phoneLabel:"(510) 239-4751",
    website:"https://www.crispianbakery.com/", menuUrl:"https://www.crispianbakery.com/menu", reserve:"https://www.crispianbakery.com/shop",
    hours:[[[7.5,15]],[],[[7.5,15]],[[7.5,15]],[[7.5,15]],[[7.5,15]],[[7.5,15]]],
    menu:[
      {sec:"Croissants & Pastries",items:[{n:"All-Butter Croissant",d:"Classic flaky laminated croissant",p:"$4.50"},{n:"Almond Croissant",d:"Buttery croissant, almond pastry cream",p:"$5.50"},{n:"Pain au Chocolat",d:"Croissant dough around dark chocolate",p:"$5"},{n:"Kouign Amann",d:"Caramelized, flaky Breton butter pastry",p:"$5"}]},
      {sec:"Sweets & Savory",items:[{n:"French Macarons",d:"Assorted fine French macarons",p:"$3"},{n:"Quiche",d:"Seasonal savory quiche slice",p:"$7"},{n:"Fresh Fruit Pie",d:"Seasonal fruit pie slice",p:"$7"}]}
    ]},
  { name:"Troy Greek Cuisine", emoji:"🥙", cuisine:"Mediterranean", featured:false,
    img:"",
    rating:"4.1", price:"$$", tags:["Greek","Gyro","Family-Owned","Mediterranean"], cats:["delivery"],
    desc:"A family-owned Greek restaurant in Alameda's East End serving gyros, souvlaki, moussaka and spanakopita with house tzatziki. Reasonably priced, casual Mediterranean comfort food for lunch and dinner.",
    address:"2320 Central Ave, Alameda, CA 94501", phone:"+15105222800", phoneLabel:"(510) 522-2800",
    website:"https://troygreek.com/", menuUrl:"https://troygreek.com/menu-1-col/", reserve:"https://www.opentable.com/r/troy-greek-alameda",
    hours:[[],[[11,20.5]],[[11,20.5]],[[11,20.5]],[[11,20.5]],[[11,20.5]],[[11,20.5]]],
    menu:[
      {sec:"Starters",items:[{n:"Spanakopita",d:"Spinach and feta in flaky filo dough",p:"$9"},{n:"Hummus & Pita",d:"House hummus with warm pita",p:"$8"}]},
      {sec:"Wraps & Platters",items:[{n:"Gyro Wrap",d:"Gyro meat, tzatziki, lettuce, tomato, grilled onions",p:"$13.20"},{n:"Gyros Platter",d:"Gyro meat with rice, salad and tzatziki",p:"$20.90"},{n:"Lamb Souvlaki",d:"Charbroiled lamb, rice, grilled veg, tzatziki",p:"$21"},{n:"Moussaka",d:"Layered eggplant, ground beef, béchamel",p:"$18"}]}
    ]},
  { name:"Greens & Grains", emoji:"🥗", cuisine:"Vegetarian", featured:false,
    img:"",
    rating:"4.3", price:"$", tags:["Salads","Organic","Vegan-Friendly","Healthy"], cats:["vegan"],
    desc:"A counter-service spot in the Alameda Marketplace building custom organic salads, daily soups and grain bowls, with plentiful vegan and vegetarian options plus optional Mary's rotisserie chicken.",
    address:"1650 Park St, Alameda, CA 94501", phone:"+15102394059", phoneLabel:"(510) 239-4059",
    website:"https://greensandgrains.net/", menuUrl:"https://greensandgrains.net/menu/", reserve:"https://greensandgrains.net/",
    hours:[[[11,18]],[[11,18.5]],[[11,18.5]],[[11,18.5]],[[11,18.5]],[[11,18.5]],[[11,18]]],
    menu:[
      {sec:"Signature Salads",items:[{n:"Kale Caesar Salad",d:"Chopped kale with Caesar dressing",p:"$10.95"},{n:"The Greek",d:"Greens, feta, olives, Greek dressing",p:"$10.95"}]},
      {sec:"Build Your Own",items:[{n:"Custom Salad Base",d:"Choose one or a mix of organic greens",p:"$7.95"},{n:"Add Protein",d:"Chicken, tofu or steak",p:"$2.55"},{n:"Daily Soup",d:"Two rotating soups, lighter & hearty options",p:"$6"},{n:"Quarter Rotisserie Chicken Meal",d:"Mary's roasted chicken with two salads",p:"$13"}]}
    ]},
  {"name":"Calafia Taqueria","emoji":"🌯","cuisine":"Mexican","featured":false,"img":"","rating":"4.3","price":"$","tags":["Burritos","Salsa Bar","Fish Tacos","Casual"],"cats":["delivery","breakfast"],"desc":"A brick-front West End neighborhood taqueria known for generous burritos, fajitas, and a self-serve bar with about eight house salsas. A longtime Webster Street favorite for hearty, affordable Mexican plates.","address":"1445 Webster St, Alameda, CA 94501","phone":"+15105222996","phoneLabel":"(510) 522-2996","website":"https://taqueriacalafia.com/","menuUrl":"https://taqueriacalafia.com/menu","reserve":"https://www.calafiataqueria.com/online-ordering","hours":[[[11,19]],[[11,15]],[[11,19]],[[11,19]],[[11,20]],[[11,21]],[[11,21]]],"menu":[{"sec":"Burritos","items":[{"n":"Super Burrito","d":"Rice, beans, choice of meat, sour cream, cheese and guacamole","p":"$15"},{"n":"Regular Burrito","d":"Rice, beans and choice of meat","p":"$13"},{"n":"Breakfast Burrito","d":"Eggs with your choice of fillings, in a flour tortilla","p":"$11"}]},{"sec":"Tacos & Plates","items":[{"n":"Soft Taco","d":"Corn tortillas with choice of meat, onions and cilantro","p":"$3.75"},{"n":"Fish Taco","d":"Battered fish with cabbage and salsa","p":"$5.25"},{"n":"Carne Asada Plate","d":"Grilled carne asada, rice, beans, guacamole, sour cream","p":"$16"},{"n":"Special Quesadilla","d":"Large quesadilla with cheese and choice of meat","p":"$6.59"}]}]},
  {"name":"Casa Revolucion Taqueria","emoji":"🌮","cuisine":"Mexican","featured":false,"img":"","rating":"4.0","price":"$","tags":["Street Tacos","Salsa Bar","Breakfast","Aguas Frescas"],"cats":["delivery","breakfast"],"desc":"A colorful Santa Clara Avenue taqueria serving street tacos, oversized burritos, tortas and nachos alongside a salsa bar and fresh aguas frescas. Open early for chilaquiles and huevos rancheros.","address":"2522 Santa Clara Ave, Alameda, CA 94501","phone":"+15102178959","phoneLabel":"(510) 217-8959","website":"https://casarevoluciontaqueriaca.com/","menuUrl":"https://casarevoluciontaqueriaca.com/","reserve":"https://order.online/en/store/taqueria-casa-revolucion-santa-clara-ave-2861694","hours":[[[8,21]],[[10,21]],[[10,21]],[[10,21]],[[10,21]],[[8,21]],[[8,21]]],"menu":[{"sec":"Tacos & Burritos","items":[{"n":"Street Taco","d":"Carne asada, al pastor, chorizo or carnitas, onion & cilantro","p":"$3"},{"n":"Super Burrito","d":"Choice of meat, rice, beans, cheese, sour cream, guacamole","p":"$15.25"},{"n":"XXL Carne Asada Burrito","d":"Over-a-pound carne asada burrito loaded with fillings","p":"$23.50"}]},{"sec":"More","items":[{"n":"Torta","d":"Mexican sandwich, protein, beans, lettuce, guacamole, jalapeños","p":"$12"},{"n":"Super Nachos","d":"Chips, meat, cheese, beans, sour cream, guacamole","p":"$14"},{"n":"Combo w/ Two Enchiladas","d":"Two enchiladas with rice and beans","p":"$14.25"}]}]},
  {"name":"Taqueria Mi Burrito","emoji":"🌯","cuisine":"Mexican","featured":false,"img":"","rating":"4.3","price":"$","tags":["Burritos","Carnitas","Old-School","Patio"],"cats":["patio"],"desc":"A counter-serve neighborhood taqueria on Alameda Avenue in the longtime Ramiro & Sons space (est. 1985), keeping the same cooks, menu and vintage sign. Known for carnitas, chile verde and chicharrones.","address":"2321 Alameda Ave, Alameda, CA 94501","phone":"+15102638144","phoneLabel":"(510) 263-8144","website":"https://www.facebook.com/taqueriamiburrito/","menuUrl":"https://taqueria-mi-burrito.wheree.com/menu","reserve":"","hours":[[[11,20]],[],[[11,20]],[[11,20]],[[11,20]],[[11,20]],[[11,20]]],"menu":[{"sec":"Burritos","items":[{"n":"Super Carnitas Burrito","d":"Carnitas, rice, beans, cheese, sour cream, guacamole","p":"$13.50"},{"n":"Chile Verde Super Burrito","d":"Pork in green chile sauce with rice, beans and fixings","p":"$13.50"},{"n":"Regular Carnitas Burrito","d":"Carnitas with rice and beans","p":"$11"}]},{"sec":"Tacos & Specialties","items":[{"n":"Super Taco Carnitas","d":"Loaded carnitas taco with fixings","p":"$5"},{"n":"Supreme Quesadilla","d":"Large quesadilla with cheese and choice of meat","p":"$10"},{"n":"Chicharrones","d":"Fried pork in salsa, a house specialty","p":"$11"}]}]},
  {"name":"Island Taqueria","emoji":"🌮","cuisine":"Mexican","featured":false,"img":"","rating":"4.2","price":"$","tags":["Tacos","Breakfast Burrito","Carne Asada Fries","Takeout"],"cats":["delivery","breakfast"],"desc":"A Park Street taqueria serving classic Mexican counter fare including breakfast burritos, tacos and loaded carne asada fries. A convenient downtown Alameda spot for quick takeout.","address":"1513 Park St, Alameda, CA 94501","phone":"+15107497018","phoneLabel":"(510) 749-7018","website":"https://www.yelp.com/biz/island-taqueria-alameda","menuUrl":"https://www.yelp.com/biz/island-taqueria-alameda","reserve":"","hours":[[],[[10,20]],[[10,20]],[[10,20]],[[10,20]],[[10,20]],[[10,20]]],"menu":[{"sec":"Burritos & Tacos","items":[{"n":"Breakfast Burrito","d":"Eggs, potatoes and choice of meat in a flour tortilla","p":"$11"},{"n":"Super Burrito","d":"Choice of meat, rice, beans, cheese, sour cream, guacamole","p":"$14"},{"n":"Carne Asada Taco","d":"Grilled steak with onion, cilantro and salsa","p":"$4"}]},{"sec":"Specialties","items":[{"n":"Carne Asada Fries","d":"Fries topped with carne asada, cheese, sour cream, guacamole","p":"$13"},{"n":"Quesadilla","d":"Cheese quesadilla with choice of meat","p":"$9"},{"n":"Nachos","d":"Chips with cheese, beans, meat and toppings","p":"$12"}]}]},
  {"name":"Spice I Am","emoji":"🍛","cuisine":"Thai","featured":false,"img":"","rating":"4.0","price":"$","tags":["Thai","Curry","Noodles","Lunch Specials"],"cats":["delivery"],"desc":"A popular downtown Alameda Thai spot on Park Street known for authentic curries, pad thai and weekday lunch specials. Praised for its green curry and tom kha soup.","address":"1353 Park St, Alameda, CA 94501","phone":"+15105228679","phoneLabel":"(510) 522-8679","website":"https://spice-i-am.com/","menuUrl":"https://spice-i-am.com/menu","reserve":"","hours":[[[11,20.5]],[[11,20.5]],[[11,20.5]],[[11,20.5]],[[11,20.5]],[[11,20.5]],[[11,20.5]]],"menu":[{"sec":"Starters & Soups","items":[{"n":"Fresh Spring Rolls","d":"Soft rice-paper rolls with herbs and vegetables","p":"$9"},{"n":"Chicken Satay","d":"Grilled marinated chicken skewers with peanut sauce","p":"$12"},{"n":"Tom Kha Goong","d":"Coconut-milk soup with prawns, galangal, lemongrass","p":"$16"}]},{"sec":"Curries & Noodles","items":[{"n":"Thai Green Curry","d":"Coconut green curry with choice of protein","p":"$18"},{"n":"Red Curry","d":"Classic Thai red coconut curry with bamboo and basil","p":"$18"},{"n":"Pad Thai","d":"Rice noodles, egg, bean sprouts, peanuts, tamarind","p":"$16"},{"n":"Pineapple Fried Rice","d":"Fried rice with pineapple, cashews and curry powder","p":"$16"}]}]},
  {"name":"Hong Kong City Restaurant","emoji":"🥢","cuisine":"Chinese","featured":false,"img":"","rating":"4.3","price":"$","tags":["Hong Kong Style","Cantonese","Noodles","Cafe"],"cats":["delivery"],"desc":"A Park Street Chinese cafe blending traditional Hong Kong culinary style with premium ingredients. Known for baked pork chop over rice and pan-fried noodles.","address":"1425 Park St, Alameda, CA 94501","phone":"+15105234568","phoneLabel":"(510) 523-4568","website":"https://alamedahongkongcity.com/","menuUrl":"https://alamedahongkongcity.com/order/","reserve":"","hours":[[[11.5,20.5]],[[11,21]],[[11,21]],[[11,21]],[[11,21]],[[11,21]],[[11,21]]],"menu":[{"sec":"Signature","items":[{"n":"Baked Pork Chop Over Rice","d":"HK-style crispy pork chop baked over rice in tomato sauce","p":"$20"},{"n":"House Pan-Fried Noodles","d":"Crispy pan-fried noodles with gravy and mixed toppings","p":"$16"},{"n":"Roasted Squab","d":"Cantonese-style roasted squab, crisp skin","p":"$18"}]},{"sec":"Noodles & Rice","items":[{"n":"Dry Style Chow Fun","d":"Wok-fried wide rice noodles with beef and bean sprouts","p":"$15"},{"n":"Wonton Noodle Soup","d":"Egg noodles in broth with shrimp-and-pork wontons","p":"$13"},{"n":"Fried Rice","d":"Cantonese fried rice with egg and choice of protein","p":"$14"}]}]},
  {"name":"Kitchen of Alameda","emoji":"🦆","cuisine":"Chinese","featured":false,"img":"","rating":"4.2","price":"$","tags":["Cantonese","Dim Sum","Roast Meats","Seafood"],"cats":["delivery"],"desc":"A West End Cantonese restaurant serving authentic roast meats, dim sum, clay-pot dishes and live seafood for over a decade. Known for roast duck and char siu.","address":"1727 Webster St, Alameda, CA 94501","phone":"+15108651662","phoneLabel":"(510) 865-1662","website":"https://kitchenof-alameda.com/","menuUrl":"https://www.kitchenofalameda.com/","reserve":"","hours":[[[10.5,20.5]],[[11.5,20.5]],[[11.5,20.5]],[[11.5,20.5]],[[11.5,20.5]],[[11.5,20.5]],[[10.5,20.5]]],"menu":[{"sec":"Roast Meats","items":[{"n":"Cantonese Roast Duck","d":"Roasted duck with crisp skin and tender meat","p":"$18"},{"n":"Char Siu Roast Pork","d":"Sweet barbecued pork with caramelized edges","p":"$16"},{"n":"Peking Duck","d":"Crispy roasted duck with pancakes and hoisin","p":"$45"}]},{"sec":"Dim Sum & Noodles","items":[{"n":"Steamed Pork Spare Ribs","d":"Bite-size ribs steamed with black bean and garlic","p":"$7"},{"n":"Roast Duck Noodle Soup","d":"Egg noodles in broth topped with roast duck","p":"$15"},{"n":"Wonton Noodle Soup","d":"Shrimp-and-pork wontons with noodles","p":"$13"}]}]},
  {"name":"Sidestreet Pho","emoji":"🍜","cuisine":"Vietnamese","featured":false,"img":"","rating":"3.9","price":"$","tags":["Vietnamese","Pho","Banh Mi","Garlic Noodles"],"cats":["delivery"],"desc":"A contemporary Vietnamese spot serving pho, bun, banh mi and street-food dishes inspired by chef Hanh Nguyen's Saigon childhood. Popular for oxtail pho and shaken beef.","address":"2304 Encinal Ave, Alameda, CA 94501","phone":"+15108085298","phoneLabel":"(510) 808-5298","website":"https://www.sidestreetpho.com/","menuUrl":"https://www.sidestreetpho.com/menu/","reserve":"https://www.yelp.com/reservations/sidestreet-pho-alameda","hours":[[[11,14.5]],[[11,14.5]],[[11,14.5]],[],[[11,14.5]],[[11,14.5]],[[11,14.5]]],"menu":[{"sec":"Starters & Pho","items":[{"n":"Fresh Veggie Spring Rolls","d":"Rice-paper rolls with herbs, vermicelli and vegetables","p":"$9"},{"n":"Pho Dac Biet","d":"House combo beef pho: rare steak, brisket and meatball","p":"$19"},{"n":"Oxtail Pho","d":"Rich beef broth with slow-cooked oxtail and rice noodles","p":"$20"}]},{"sec":"Rice & Noodles","items":[{"n":"Shaken Beef with Garlic Noodles","d":"Wok-seared cubed beef over buttery garlic noodles","p":"$22"},{"n":"Grilled Pork Banh Mi","d":"Baguette with grilled pork, pickled veg and herbs","p":"$12"},{"n":"Chicken Porridge","d":"Rice congee with chicken and a savory donut","p":"$14"}]}]},
  {"name":"Vietnam House","emoji":"🍲","cuisine":"Vietnamese","featured":false,"img":"","rating":"4.1","price":"$","tags":["Vietnamese","Pho","Rice Plates","Banh Mi"],"cats":["delivery"],"desc":"A Park Street neighborhood Vietnamese restaurant serving authentic pho, vermicelli bowls, rice plates and banh mi. Family-friendly with take-out and delivery.","address":"1529 Park St, Alameda, CA 94501","phone":"+15108644022","phoneLabel":"(510) 864-4022","website":"https://vietnamhousealameda.mybistro.online/","menuUrl":"https://vietnamhousealameda.mybistro.online/","reserve":"","hours":[[[11,19.5]],[[11,20]],[],[[11,20]],[[11,20]],[[11,20]],[[11,20]]],"menu":[{"sec":"Appetizers","items":[{"n":"Shrimp Spring Rolls","d":"Fresh rolls with shrimp, vermicelli, herbs and peanut sauce","p":"$12"},{"n":"BBQ Pork Spring Rolls","d":"Grilled pork wrapped with vegetables and herbs","p":"$7.50"},{"n":"Chicken and Mango Salad","d":"Shredded chicken with mango, herbs and tangy dressing","p":"$9"}]},{"sec":"Pho & Banh Mi","items":[{"n":"Rare Steak & Brisket Pho","d":"Beef noodle soup with rare steak and brisket","p":"$18"},{"n":"Chicken Pho","d":"Rice-noodle soup with poached chicken in clear broth","p":"$17"},{"n":"Grilled Pork Banh Mi","d":"Baguette with grilled pork, pickled carrots and cilantro","p":"$10"}]}]},
  {"name":"Hashi Gawa","emoji":"🍣","cuisine":"Japanese","featured":false,"img":"","rating":"4.5","price":"$$","tags":["Sushi","Ramen","Omakase","Japanese"],"cats":["delivery"],"desc":"A well-regarded Alameda sushi and ramen spot in the Bridgeside Shopping Center known for fresh nigiri, omakase, and hearty kaisen don. A go-to for quality Japanese seafood.","address":"2661 Blanding Ave, Alameda, CA 94501","phone":"+15102275187","phoneLabel":"(510) 227-5187","website":"https://hashi-gawa.wheree.com/","menuUrl":"https://www.doordash.com/store/hashi-gawa-alameda-2301846/","reserve":"","hours":[[[12,15.5],[16.5,21]],[],[[16.5,21.5]],[[11.5,14.5],[16.5,21.5]],[[11.5,14.5],[16.5,21.5]],[[11.5,14.5],[16.5,21.5]],[[12,15.5],[16.5,21.5]]],"menu":[{"sec":"Omakase & Signature","items":[{"n":"Omakase (10 pc Nigiri)","d":"Chef's selection of ten seasonal nigiri with miso soup and salad","p":"$58"},{"n":"Hashi Kaisen Don","d":"Seafood rice bowl topped with assorted fresh sashimi","p":"$45"},{"n":"Hashi Sushi Combo","d":"Generous combination of nigiri and a roll","p":"$32"}]},{"sec":"Ramen & Starters","items":[{"n":"Tonkotsu Ramen","d":"Rich pork-bone broth with fresh noodles, chashu and toppings","p":"$16"},{"n":"Seafood Yaki Udon","d":"Stir-fried thick udon with mixed seafood and vegetables","p":"$18"},{"n":"Spicy Garlic Edamame","d":"Steamed soybeans tossed in spicy garlic sauce","p":"$8"}]}]},
  {"name":"Waki Japanese Cuisine","emoji":"🍱","cuisine":"Japanese","featured":false,"img":"","rating":"4.6","price":"$$","tags":["Sushi","Sashimi","Izakaya","Japanese"],"cats":["delivery"],"desc":"An intimate Webster Street sushi bar opened in 2022 focused on fresh ingredients, skilled craftsmanship and warm hospitality. Known for creative dragon rolls and tuna tataki.","address":"1403 Webster St, Alameda, CA 94501","phone":"+15102178396","phoneLabel":"(510) 217-8396","website":"https://www.wakisushi1403.com/","menuUrl":"https://www.wakisushi1403.com/","reserve":"","hours":[[[12,14.5],[16,21]],[[17,21]],[[17,21]],[[17,21]],[[17,21]],[[17,21]],[[17,21]]],"menu":[{"sec":"Signature Rolls","items":[{"n":"Red Dragon Roll","d":"Roll topped with spicy tuna and avocado","p":"$18"},{"n":"Lion King Roll","d":"Baked salmon roll with creamy sauce","p":"$19"},{"n":"Rainbow Roll","d":"California roll wrapped in assorted sashimi","p":"$20"}]},{"sec":"Sashimi & Apps","items":[{"n":"Bluefin Tuna Tataki","d":"Lightly seared bluefin tuna with ponzu","p":"$18"},{"n":"Hamachi Carpaccio","d":"Thin-sliced yellowtail with citrus and jalapeño","p":"$17"},{"n":"Shrimp Tempura","d":"Crispy battered shrimp","p":"$12"}]}]},
  {"name":"Tang Jip","emoji":"🍲","cuisine":"Korean","featured":false,"img":"","rating":"4.3","price":"$","tags":["Korean","Bibimbap","Comfort Food","Stews"],"cats":["delivery"],"desc":"A comfortable Korean restaurant at South Shore Center serving authentic homestyle dishes with quality ingredients. Popular for stone-pot bibimbap, soon tofu stew and Korean fried chicken.","address":"2201 S Shore Ctr, Alameda, CA 94501","phone":"+15102638717","phoneLabel":"(510) 263-8717","website":"https://tangjip.com/","menuUrl":"https://tangjip.com/MENU","reserve":"","hours":[[[11,21]],[[11,21]],[[11,21]],[[11,21]],[[11,21]],[[11,21]],[[11,21]]],"menu":[{"sec":"Rice & Stews","items":[{"n":"Dolsot Bibimbap","d":"Sizzling stone-pot rice with vegetables, egg and beef","p":"$22"},{"n":"Soon Tofu","d":"Spicy soft tofu stew with seafood or beef","p":"$21"},{"n":"Galbitang","d":"Clear beef short-rib soup","p":"$26"}]},{"sec":"Plates & Sides","items":[{"n":"Japchae","d":"Stir-fried glass noodles with vegetables","p":"$15"},{"n":"Seafood Pancake","d":"Crispy pan-fried pancake with seafood and scallions","p":"$18"},{"n":"Korean Fried Chicken Wings","d":"Crispy wings in a savory-sweet glaze","p":"$16"}]}]},
  {"name":"Ohgane KBBQ x Vons Chicken","emoji":"🥩","cuisine":"Korean","featured":false,"img":"","rating":"4.2","price":"$$","tags":["Korean BBQ","AYCE","Grill","Fried Chicken"],"cats":["delivery"],"desc":"All-you-can-eat Korean barbecue at South Shore Center where you grill premium marinated meats tableside with a rotating spread of banchan, plus a Vons Chicken add-on for Korean fried chicken.","address":"2211 S Shore Ctr, Ste 160, Alameda, CA 94501","phone":"+15107757538","phoneLabel":"(510) 775-7538","website":"https://ohgane.com/alameda-location","menuUrl":"https://ohgane.menu11.com/alameda/order","reserve":"","hours":[[[11,21]],[[11,21]],[[11,21]],[[11,21]],[[11,22]],[[11,22]],[[11,21]]],"menu":[{"sec":"All-You-Can-Eat","items":[{"n":"AYCE Combo","d":"Unlimited galbi, bulgogi, spicy pork, brisket, banchan, rice","p":"$38"},{"n":"Premium AYCE","d":"AYCE plus premium meat selections","p":"$48"},{"n":"Lunch AYCE (Mon-Fri)","d":"Weekday lunch all-you-can-eat, 11am-2pm","p":"$33"}]},{"sec":"Grill & Vons Chicken","items":[{"n":"Galbi","d":"Marinated beef short rib for the grill","p":"$29"},{"n":"Bulgogi","d":"Thin-sliced marinated ribeye","p":"$25"},{"n":"Original Fried Chicken","d":"Signature crispy Korean fried chicken","p":"$18"}]}]},
  {"name":"Shanvi Indian Kitchen & Grocery","emoji":"🍛","cuisine":"Indian","featured":false,"img":"","rating":"4.4","price":"$","tags":["Indian","Curry","Tandoori","Vegan-Friendly"],"cats":["delivery","vegan"],"desc":"A women-owned Santa Clara Avenue spot combining a homestyle Indian kitchen with an Indian and Middle Eastern grocery. Known for flaky samosas, rich curries and tandoori with many vegan options.","address":"2536 Santa Clara Ave, Alameda, CA 94501","phone":"+15102394665","phoneLabel":"(510) 239-4665","website":"https://www.shanviindiankitchen.com/","menuUrl":"https://www.shanviindiankitchen.com/menu","reserve":"","hours":[[[10,21]],[[10,21]],[[10,21]],[[10,21]],[[10,21]],[[10,21]],[[10,21]]],"menu":[{"sec":"Appetizers","items":[{"n":"Vegetable Samosa (2)","d":"Crispy pastry stuffed with spiced potatoes and peas","p":"$7.99"},{"n":"Chicken Samosa (2)","d":"Fried pastry filled with spiced minced chicken","p":"$7.99"},{"n":"Aloo Tikki","d":"Vegan spiced potato patties","p":"$5.99"}]},{"sec":"Curries & Combos","items":[{"n":"Chicken Tikka Masala","d":"Grilled chicken in a creamy spiced tomato sauce","p":"$14.99"},{"n":"Lamb Rogan Josh","d":"Tender lamb simmered in aromatic curry","p":"$17.99"},{"n":"Shanvi Special Combo","d":"Vegetable, chicken, lamb, rice, naan, samosa and mango lassi","p":"$22.99"}]}]},
  {"name":"Julie's Coffee & Tea Garden","emoji":"☕","cuisine":"Cafe","featured":false,"img":"","rating":"4.3","price":"$","tags":["Coffee","Loose-Leaf Tea","Vegan-Friendly","Brunch"],"cats":["breakfast","vegan","patio"],"desc":"A cozy Park Street cafe serving espresso, loose-leaf teas and wholesome breakfast fare made with premium ingredients. Known for inspired pastries plus generous gluten-free and vegan options.","address":"1223 Park St, Alameda, CA 94501","phone":"+15108652385","phoneLabel":"(510) 865-2385","website":"https://juliestea.com/alameda/","menuUrl":"https://order.juliestea.com/","reserve":"","hours":[[[7,16]],[[7,16]],[[7,16]],[[7,16]],[[7,16]],[[7,16]],[[7,16]]],"menu":[{"sec":"Drinks","items":[{"n":"Latte","d":"Espresso with steamed milk; oat or almond available","p":"$5"},{"n":"Loose-Leaf Tea Pot","d":"House selection of premium loose-leaf teas by the pot","p":"$5"},{"n":"Herbal Tonic","d":"House-made herbal tonic beverage","p":"$6"}]},{"sec":"Food","items":[{"n":"Avocado Toast","d":"Smashed avocado on sourdough with cilantro (vegan)","p":"$12"},{"n":"Breakfast Plate","d":"Eggs with toast and seasonal sides","p":"$13"},{"n":"Soup & Salad","d":"Daily soup paired with a fresh green salad","p":"$12"},{"n":"Inspired Pastry","d":"Rotating scones and pastries; vegan & GF options","p":"$5"}]}]},
  {"name":"SIGNAL Coffee Roasters","emoji":"🍩","cuisine":"Cafe","featured":false,"img":"","rating":"4.5","price":"$","tags":["Specialty Coffee","Roaster","Donuts","Pastries"],"cats":["breakfast"],"desc":"A Webster Street specialty roaster serving house-roasted small-batch coffee and custom signature drinks. Beloved for gourmet donuts and rotating pastries from top Northern California bakeries.","address":"1536 Webster St, Alameda, CA 94501","phone":"+15102178739","phoneLabel":"(510) 217-8739","website":"https://signalcoffee.com/","menuUrl":"https://www.signalcoffeeonline.com/","reserve":"","hours":[[[7,17]],[[7,16]],[[7,16]],[[7,16]],[[7,16]],[[7,17]],[[7,17]]],"menu":[{"sec":"Signature Drinks","items":[{"n":"Latte","d":"House-roasted espresso with steamed milk","p":"$5"},{"n":"Ube Latte","d":"Signature latte with purple yam, subtly sweet and nutty","p":"$6"},{"n":"Black Sesame Latte","d":"Toasted black sesame latte with a roasty finish","p":"$6"},{"n":"Cafe Bombon","d":"Espresso layered with sweetened condensed milk","p":"$5"}]},{"sec":"Bakes","items":[{"n":"Gourmet Donut","d":"Rotating gourmet donuts sourced daily","p":"$4"},{"n":"In-House Bake","d":"Fresh in-house pastries baked daily","p":"$4"}]}]},
  {"name":"Cafe Jolie","emoji":"🥐","cuisine":"Cafe","featured":false,"img":"","rating":"4.4","price":"$","tags":["French","Brunch","Beignets","Breakfast"],"cats":["breakfast"],"desc":"A charming French-American cafe on Webster Street serving classic egg dishes, croque monsieur, and famous powdered-sugar beignets. Weekend brunch plus Thursday-Saturday dinner service.","address":"1500 Webster St, Alameda, CA 94501","phone":"+15105234500","phoneLabel":"(510) 523-4500","website":"http://www.cafejolies.com/","menuUrl":"https://www.opentable.com/r/cafe-jolie","reserve":"https://www.opentable.com/r/cafe-jolie","hours":[[[8,14]],[],[[9,13]],[[9,13]],[[9,13],[17,21.5]],[[9,13],[17,21.5]],[[8,14],[17,21.5]]],"menu":[{"sec":"Breakfast & Brunch","items":[{"n":"La Campagne Omelette","d":"Country-style omelette with seasonal fillings","p":"$14"},{"n":"Croque Monsieur","d":"Toasted ham and cheese with béchamel and a fried egg","p":"$16"},{"n":"Crab Cake Benedict","d":"Poached eggs over crab cakes with hollandaise","p":"$18"},{"n":"Beignets","d":"Fried pastry with powdered sugar, berries and ganache","p":"$10.50"}]},{"sec":"Dinner","items":[{"n":"Steak Frites","d":"Grilled steak with French fries","p":"$28"},{"n":"Salmon Florentine","d":"Poached eggs and salmon over spinach, hollandaise","p":"$18"}]}]},
  {"name":"Lazybird Coffee","emoji":"🥪","cuisine":"Cafe","featured":false,"img":"","rating":"4.4","price":"$","tags":["Coffee","Specialty Lattes","Sandwiches","Brunch"],"cats":["breakfast"],"desc":"A laid-back Central Avenue coffee shop known for creative specialty lattes and hearty sandwiches. Standout bread pudding and congee make it a favorite morning stop.","address":"930 Central Ave, Alameda, CA 94501","phone":"+15102638057","phoneLabel":"(510) 263-8057","website":"https://www.lazybirdcoffee.com/","menuUrl":"https://www.lazybirdcoffee.com/menu","reserve":"","hours":[[[7.5,14]],[[7.5,14]],[[7.5,14]],[[7.5,14]],[[7.5,14]],[[7.5,14]],[[7.5,14]]],"menu":[{"sec":"Specialty Lattes","items":[{"n":"Honey Lavender Latte","d":"Latte with house honey lavender syrup","p":"$6"},{"n":"Ube Latte","d":"Purple yam latte, sweet and creamy","p":"$6"},{"n":"Pandan Latte","d":"Fragrant pandan-infused latte","p":"$6"},{"n":"Horchata Latte","d":"Cinnamon rice-milk horchata blended with espresso","p":"$6"}]},{"sec":"Food","items":[{"n":"The Lazybird Roast","d":"Turkey, brie, arugula, basil, aioli and Dijon","p":"$13"},{"n":"Kalua Pork Sandwich","d":"Slow-cooked Hawaiian-style pulled pork","p":"$13"},{"n":"Bread Pudding","d":"House-made standout bread pudding","p":"$6"}]}]},
  {"name":"House of Bagels","emoji":"🥯","cuisine":"Cafe","featured":false,"img":"","rating":"4.3","price":"$","tags":["Bagels","Bakery","Breakfast Sandwiches","Lox"],"cats":["breakfast"],"desc":"A Park Street bakery baking bagels in-house daily with all-natural ingredients. Popular for everything bagels with veggie schmear, lox, and warm egg-and-cheese breakfast sandwiches.","address":"1362 Park St, Alameda, CA 94501","phone":"+15105226580","phoneLabel":"(510) 522-6580","website":"https://www.houseofbagels.co/locations","menuUrl":"https://www.allmenus.com/ca/alameda/1022313-house-of-bagels/menu/","reserve":"","hours":[[[6,17.5]],[[6,17.5]],[[6,17.5]],[[6,17.5]],[[6,17.5]],[[6,17.5]],[[6,17.5]]],"menu":[{"sec":"Bagels","items":[{"n":"Individual Bagel","d":"House-baked bagel, choice of flavor","p":"$2.50"},{"n":"Double Jalapeno Cheddar Bagel","d":"Spicy bagel loaded with jalapeño and cheddar","p":"$3.50"},{"n":"Cragel","d":"Croissant-bagel hybrid, flaky and chewy","p":"$4.50"}]},{"sec":"Sandwiches","items":[{"n":"Lox & Cream Cheese Bagel","d":"Traditional bagel with lox and cream cheese","p":"$12"},{"n":"Breakfast Omelette Bagel","d":"Warm bagel with egg, cheese and choice of protein","p":"$8"},{"n":"Everything Bagel w/ Veggie Schmear","d":"Crisp chewy everything bagel with veggie cream cheese","p":"$5"}]}]},
  {"name":"1400 Bar & Grill","emoji":"🍔","cuisine":"American","featured":false,"img":"","rating":"4.2","price":"$","tags":["Gastropub","Burgers","Full Bar","Brunch"],"cats":["patio","breakfast","delivery"],"desc":"A lively neighborhood gastropub in an 1880s former hotel on Webster Street, serving burgers, pizzas, comfort classics and daily specials with a full bar. A West End mainstay with weekend brunch.","address":"1400 Webster St, Alameda, CA 94501","phone":"+15102639651","phoneLabel":"(510) 263-9651","website":"https://1400barandgrillalamedaca.com/","menuUrl":"https://1400barandgrillalamedaca.com/food-menu","reserve":"","hours":[[[10,21]],[[11,22]],[[11,22]],[[11,22]],[[11,22]],[[11,23]],[[10,23]]],"menu":[{"sec":"Starters","items":[{"n":"BBQ Pork Nachos","d":"Chips piled with pulled BBQ pork, melted cheese and jalapeños","p":"$14"},{"n":"Clam Chowder","d":"Creamy New England-style clam chowder","p":"$9"},{"n":"Crab Sandwich","d":"Classic Dungeness-style crab sandwich","p":"$10"}]},{"sec":"Burgers & Mains","items":[{"n":"Chili Burger","d":"8 oz patty topped with house chili and cheese","p":"$11"},{"n":"Lamb Burger","d":"Seasoned ground lamb patty with fixings","p":"$11"},{"n":"Fish & Chips","d":"Beer-battered cod with shoestring chips and tartar","p":"$16"},{"n":"Mac and Cheese","d":"Baked creamy three-cheese macaroni","p":"$13"}]}]},
  {"name":"The Bureau 510","emoji":"🍔","cuisine":"American","featured":false,"img":"","rating":"4.4","price":"$","tags":["Burgers","Craft Cocktails","Sandwiches","Casual"],"cats":["patio","delivery"],"desc":"A stylish Webster Street burger spot serving gourmet burgers on ACME buns, hand-cut Parmesan fries and craft cocktails. A pet-friendly West End favorite with a laid-back vibe.","address":"1531 Webster St, Alameda, CA 94501","phone":"+15106712262","phoneLabel":"(510) 671-2262","website":"https://thebureau510.com/","menuUrl":"https://thebureau510.com/","reserve":"","hours":[[[11.5,20.5]],[[11.5,20.5]],[[11.5,20.5]],[[11.5,20.5]],[[11.5,20.5]],[[11.5,20.5]],[[11.5,20.5]]],"menu":[{"sec":"Burgers","items":[{"n":"B-B-B Burger","d":"Bacon, caramelized onion butter, Point Reyes blue, garlic mayo","p":"$14"},{"n":"No. 27 Burger","d":"Butter lettuce, tomato, onion, cheddar and pickles","p":"$12"},{"n":"Nostalgia Burger","d":"Butter lettuce, tomato, caramelized onion, American cheese","p":"$11"}]},{"sec":"Sides & More","items":[{"n":"Parmesan Fries","d":"Hand-cut fries with Parmesan and Sriracha mayo","p":"$8"},{"n":"IPA Onion Rings","d":"Beer-battered onion rings","p":"$8"},{"n":"Fish N Chips","d":"IPA-battered wild cod, Parmesan fries, spicy remoulade","p":"$18"}]}]},
  {"name":"Hang Ten Boiler","emoji":"🦞","cuisine":"Seafood","featured":false,"img":"","rating":"4.3","price":"$","tags":["Cajun Boil","Hawaiian","Crab","Garlic Noodles"],"cats":["delivery"],"desc":"A family-owned Santa Clara Avenue spot blending Hawaiian plate favorites with Cajun-style seafood boils. Known for crab, crawfish and shrimp by the pound in signature sauces, plus garlic noodles.","address":"2315 Santa Clara Ave, Alameda, CA 94501","phone":"+15102638688","phoneLabel":"(510) 263-8688","website":"https://hangtenboiler.com/","menuUrl":"https://hangtenboiler.com/alameda-hang-ten-boiler-food-menu","reserve":"","hours":[[[11,21]],[[11,21]],[[11,21]],[[11,21]],[[11,21]],[[11,21]],[[11,21]]],"menu":[{"sec":"Appetizers","items":[{"n":"Fried Pork Lumpia","d":"Ten crispy fried pork rolls with sweet chili sauce","p":"$10"},{"n":"Garlic Shrimp","d":"Hawaiian-style sautéed garlic shrimp","p":"$14"},{"n":"Kalua Pork Fries","d":"Fries topped with kalua pork, aioli and green onion","p":"$12"}]},{"sec":"Boil & Plates","items":[{"n":"Shrimp Boil","d":"One pound of shrimp in your choice of sauce and spice","p":"$23"},{"n":"Half and Half Boil","d":"Two seafood choices with corn and potato","p":"$25"},{"n":"Garlic Noodles","d":"House garlic butter noodles, a signature favorite","p":"$16"},{"n":"Hawaiian Teriyaki Steak","d":"Grilled teriyaki-marinated steak plate","p":"$18"}]}]},
  {"name":"Asena Restaurant","emoji":"🥘","cuisine":"Mediterranean","featured":false,"img":"","rating":"4.4","price":"$$","tags":["Mediterranean","Mezze","Wine Bar","Courtyard"],"cats":["patio"],"desc":"A long-running Santa Clara Avenue destination serving Mediterranean cuisine with Turkish, Greek and Italian influences, house-made focaccia and an extensive wine list. Features a charming courtyard.","address":"2508 Santa Clara Ave, Alameda, CA 94501","phone":"+15105214100","phoneLabel":"(510) 521-4100","website":"https://asenarestaurant.com/","menuUrl":"https://asenarestaurant.com/menu/","reserve":"https://www.opentable.com/r/asena-alameda","hours":[[],[[17,21]],[[17,21]],[[17,21]],[[17,21]],[[17,22]],[[17,22]]],"menu":[{"sec":"Mezzes","items":[{"n":"Hummus with Linguica","d":"House-made hummus topped with linguica and flatbread","p":"$14"},{"n":"Warm Burrata","d":"Warm burrata with plum tomato sauce and fresh basil","p":"$15"},{"n":"Spinach Filo Triangles","d":"Crispy filo with spinach, Turkish feta and onion","p":"$14"},{"n":"Steamed Mussels","d":"Mussels with spinach in sun-dried tomato cream","p":"$22"}]},{"sec":"Entrees","items":[{"n":"Baked Eggplant with Lamb","d":"Ground lamb baked in eggplant, Mediterranean-spiced","p":"$18"},{"n":"Paella","d":"Saffron rice with seafood and meats","p":"$32"},{"n":"Lamb with Gruyere and Marsala","d":"Lamb finished in Gruyère and Marsala sauce","p":"$34"}]}]},
  {"name":"Scolari's Good Eats","cuisine":"American","featured":false,"img":"","rating":"4.4","price":"$","tags":["Burgers","Fried Chicken","East Coast","Craft Beer"],"cats":["delivery"],"desc":"Park Street's beloved burger-and-fried-chicken spot serving made-from-scratch comfort food with an East Coast edge — famous for the Nashville Hot chicken sandwich and inventive stacked burgers. Featured on Food Network.","address":"1303 Park St, Alameda, CA 94501","phone":"+15105212400","phoneLabel":"(510) 521-2400","website":"https://www.scolarisgoodeats.com/","menuUrl":"https://www.scolarisgoodeats.com/","reserve":"https://slicelife.com/restaurants/ca/alameda/94501/scolari-s-good-eats/menu","hours":[[[11.5,21]],[[11.5,21]],[[11.5,21]],[[11.5,21]],[[11.5,23]],[[11.5,23]],[[11.5,23]]],"menu":[{"sec":"Burgers","items":[{"n":"Blueberry Bacon Blue Cheeseburger","d":"House patty, blueberry jam, bacon, blue cheese — the cult favorite","p":"$17"},{"n":"Classic Cheeseburger","d":"Smashed patty, American cheese, house sauce","p":"$14"}]},{"sec":"Chicken & Sides","items":[{"n":"Nashville Hot Chicken Sandwich","d":"Crispy fried chicken, hot oil glaze, pickles — the must-try","p":"$16"},{"n":"Crispy Fried Chicken","d":"Buttermilk-brined, fried to order","p":"$17"},{"n":"Garlic Fries","d":"Hand-cut fries, garlic and herbs","p":"$7"},{"n":"Onion Rings","d":"Beer-battered, crispy","p":"$8"}]}]},
  {"name":"Fikscue Craft BBQ","cuisine":"BBQ","featured":false,"img":"","rating":"4.7","price":"$$","tags":["Texas BBQ","Indonesian Fusion","Halal","Brisket"],"cats":[],"desc":"Halal Indo-Tex barbecue named one of America's best new restaurants — slow-smoked dino brisket and jalapeño-cheddar sausage alongside Indonesian fusion like beef rendang. Limited hours; the good stuff sells out early.","address":"1708 Park St, Ste 120, Alameda, CA 94501","phone":"+15104631303","phoneLabel":"(510) 463-1303","website":"https://www.fikscue.com/","menuUrl":"https://www.fikscue.com/alameda","reserve":"https://www.fikscue.com/alameda","hours":[[[12,17]],[],[],[[17,21]],[],[],[[12,17]]],"menu":[{"sec":"From the Smoker","items":[{"n":"Dino Brisket","d":"Massive slow-smoked beef rib — the signature","p":"$42"},{"n":"Brisket Sandwich","d":"Chopped smoked brisket on a soft roll","p":"$18"},{"n":"Jalapeño Cheddar Sausage","d":"House-made, snappy and spicy","p":"$12"}]},{"sec":"Indo Fusion","items":[{"n":"Beef Rendang","d":"BBQ technique meets Indonesian spice","p":"$22"},{"n":"Batagor","d":"Fried dumplings, peanut sauce","p":"$10"},{"n":"Indonesian Fried Rice","d":"Smoky nasi goreng","p":"$14"}]}]},
  {"name":"Burma Superstar","cuisine":"Burmese","featured":false,"img":"","rating":"4.3","price":"$","tags":["Burmese","Tea Leaf Salad","Curries","Famous"],"cats":["delivery"],"desc":"The Bay Area Burmese institution's Park Street outpost — home of the award-winning table-mixed tea leaf salad, rainbow salad, and rich Burmese curries.","address":"1345 Park St, Alameda, CA 94501","phone":"+15105226200","phoneLabel":"(510) 522-6200","website":"https://www.burmasuperstar.co/","menuUrl":"https://www.burmasuperstar.co/menu/","reserve":"https://www.opentable.com/r/burma-superstar-alameda","hours":[[[11.5,21]],[[11.5,21]],[[11.5,21]],[[11.5,21]],[[11.5,21]],[[11.5,21]],[[11.5,21]]],"menu":[{"sec":"Salads & Starters","items":[{"n":"Tea Leaf Salad","d":"Fermented tea leaves, crunchy nuts & seeds, mixed table-side — Good Food Award winner","p":"$16"},{"n":"Rainbow Salad","d":"22 ingredients: noodles, papaya, crispy bits","p":"$16"},{"n":"Platha & Dip","d":"Flaky flatbread with curry dip","p":"$9"}]},{"sec":"Mains","items":[{"n":"Fiery Chicken & Tofu","d":"Wok-fired with chili and basil","p":"$19"},{"n":"Burmese Style Curry","d":"Rich, slow-cooked house curry","p":"$20"},{"n":"Garlic Chili Shrimp","d":"Sizzling prawns, garlic, chili","p":"$22"},{"n":"Mohinga","d":"Burma's national fish-noodle soup","p":"$17"}]}]},
  {"name":"Speisekammer","cuisine":"German","featured":false,"img":"","rating":"4.2","price":"$","tags":["German","Beer Garden","Schnitzel","Live Music"],"cats":["patio"],"desc":"Alameda's beloved German restaurant and bar on Lincoln Ave — schnitzel, spätzle and schweinehaxe with a serious German beer list, a garden patio, and live bands on weekends.","address":"2424 Lincoln Ave, Alameda, CA 94501","phone":"+15105221300","phoneLabel":"(510) 522-1300","website":"https://www.speisekammer.com/","menuUrl":"https://www.speisekammer.com/","reserve":"https://www.opentable.com/r/speisekammer-alameda","hours":[[[11.5,21]],[[16.5,21]],[[16.5,21]],[[16.5,21]],[[16.5,21]],[[11.5,22]],[[11.5,22]]],"menu":[{"sec":"Classics","items":[{"n":"Wiener Schnitzel vom Schwein","d":"Two breaded pan-fried pork cutlets, roasted potatoes, German salad","p":"$22"},{"n":"Käsespätzle","d":"House spätzle baked with cheese and crispy onions","p":"$18"},{"n":"Schweinehaxe","d":"Crispy roasted pork shank","p":"$28"},{"n":"Bratwurst Plate","d":"Grilled sausages, sauerkraut, mustard","p":"$17"}]},{"sec":"To Drink & Finish","items":[{"n":"German Beer (½ liter)","d":"Rotating drafts from the motherland","p":"$9"},{"n":"Giant Pretzel","d":"Bavarian-style with mustard","p":"$8"}]}]},
  {"name":"Alley & Vine","cuisine":"American","featured":false,"img":"","rating":"4.4","price":"$$","tags":["Farm-to-Table","Californian","Cocktails","Date Night"],"cats":[],"desc":"A refined farm-to-table Californian kitchen on Park Street with a frequently-changing seasonal menu — Dungeness crab, braised short rib, locally-caught rock cod — and a polished cocktail program.","address":"1332 Park St, Ste D, Alameda, CA 94501","phone":"+15102275006","phoneLabel":"(510) 227-5006","website":"https://alleyandvine.com/","menuUrl":"https://alleyandvine.com/menus","reserve":"https://www.opentable.com/r/alley-and-vine-alameda","hours":[[[11,21]],[[11,21]],[[11,21]],[[11,21]],[[11,21]],[[11,21]],[[11,21]]],"menu":[{"sec":"Seasonal Plates","items":[{"n":"Dungeness Crab","d":"Local crab, seasonal preparation","p":"$28"},{"n":"Braised Beef Short Rib","d":"Slow-braised, seasonal sides","p":"$34"},{"n":"Locally-Caught Rock Cod","d":"From nearby waters, market preparation","p":"$30"},{"n":"Mac 'n' Cheese","d":"House favorite comfort side","p":"$14"}]},{"sec":"Dessert","items":[{"n":"Carrot Cake","d":"House-made classic","p":"$11"},{"n":"Chocolate Pot de Crème","d":"Silky dark-chocolate custard","p":"$11"}]}]},
  {"name":"Cholita Linda","cuisine":"Latin American","featured":false,"img":"","rating":"4.3","price":"$","tags":["Fish Tacos","Cubano","Aguas Frescas","Casual"],"cats":["delivery"],"desc":"The East Bay favorite's Park Street home — famous Baja fish tacos, hot-pressed Cubano sandwiches, pollo asado plates and fresh aguas frescas in a bright, casual room.","address":"1337 Park St, Alameda, CA 94501","phone":"+15102256997","phoneLabel":"(510) 225-6997","website":"https://www.cholitalinda.com/locations/alameda/","menuUrl":"https://www.cholitalinda.com/","reserve":"https://www.cholitalinda.com/locations/alameda/","hours":[[[11,21]],[[11,21]],[[11,21]],[[11,21]],[[11,21]],[[11,21]],[[11,21]]],"menu":[{"sec":"Tacos & Sandwiches","items":[{"n":"Baja Fish Tacos","d":"Crispy fish, slaw, crema — the one everyone orders","p":"$6.50"},{"n":"Cubano","d":"Hot-pressed pork, ham, swiss, pickles, mustard","p":"$15"},{"n":"Carnitas Taco","d":"Slow-cooked pork, salsa fresca","p":"$6"}]},{"sec":"Plates & Drinks","items":[{"n":"Pollo Asado Plate","d":"Marinated grilled chicken, rice, beans, salad","p":"$18"},{"n":"Aguas Frescas","d":"Daily fresh fruit coolers","p":"$5"}]}]},
  {"name":"Tucker's Ice Cream","cuisine":"Dessert","featured":false,"img":"","rating":"4.5","price":"$","tags":["Ice Cream","Since 1941","Waffle Cones","Family"],"cats":[],"desc":"Alameda's ice cream parlor since 1941 — super-creamed small-batch scoops, house waffle cones and old-fashioned sundaes on Park Street. An island institution across generations.","address":"1349 Park St, Alameda, CA 94501","phone":"+15105224960","phoneLabel":"(510) 522-4960","website":"https://tuckersicecream.com/","menuUrl":"https://tuckersicecream.com/","reserve":"https://tuckerstogo.square.site/","hours":[[[12,21]],[[12,21]],[],[[12,21]],[[12,21]],[[12,22]],[[12,22]]],"menu":[{"sec":"Scoops & Cones","items":[{"n":"Single Scoop","d":"Super-creamed small-batch ice cream","p":"$5.50"},{"n":"Fresh Waffle Cone","d":"Baked in-house all day","p":"$2.50"},{"n":"Toasted Almond","d":"The legendary house flavor","p":"$5.50"}]},{"sec":"Sundaes & Shakes","items":[{"n":"Hot Fudge Sundae","d":"Classic with house hot fudge","p":"$9"},{"n":"Milkshake","d":"Any flavor, spun thick","p":"$9"}]}]},
  {"name":"Dragon Rouge Bistro","cuisine":"Vietnamese","featured":false,"img":"","rating":"4.1","price":"$","tags":["Vietnamese","Clay Pots","Cocktails","Bistro"],"cats":["delivery"],"desc":"A stylish Vietnamese bistro on Blanding Ave inspired by the coastal city of Phan Thiet — signature Phantastic rolls, bouncing beef tenderloin, classic clay pots and lemongrass stir-fries.","address":"2337 Blanding Ave, Alameda, CA 94501","phone":"+15105211800","phoneLabel":"(510) 521-1800","website":"https://dragonrougebythebay.com/","menuUrl":"https://dragonrougebythebay.com/","reserve":"https://www.opentable.com/r/dragon-rouge-vietnamese-bistro","hours":[[[11,21.5]],[[11,21.5]],[[11,21.5]],[[11,21.5]],[[11,21.5]],[[11,21.5]],[[11,21.5]]],"menu":[{"sec":"Signatures","items":[{"n":"Phantastic Roll","d":"House signature fresh rolls","p":"$12"},{"n":"Bouncing Beef","d":"Wok-seared tenderloin cubes, the crowd favorite","p":"$24"},{"n":"Classic Clay Pot","d":"Caramelized fish or pork in a sizzling clay pot","p":"$21"}]},{"sec":"Wok & Noodles","items":[{"n":"Lemongrass Curry Stir-Fry","d":"Fragrant curry with choice of protein","p":"$19"},{"n":"Garlic Noodles","d":"Buttery, garlicky house noodles","p":"$14"}]}]},
  {"name":"Leña","cuisine":"Mexican","featured":false,"img":"","rating":"4.4","price":"$$","tags":["Modern Mexican","Birria","Weekend Brunch","Family-Owned"],"cats":["breakfast"],"desc":"A family-run modern Mexican kitchen just off Park Street — oxtail and short-rib birria, pork belly in salsa verde, whole achiote-marinated branzino, and seven signature tacos. Weekend brunch; reservations smart on weekends.","address":"2431 Central Ave, Alameda, CA 94501","phone":"+15106712197","phoneLabel":"(510) 671-2197","website":"https://lenaalameda.com/","menuUrl":"https://lenaalameda.com/","reserve":"https://lenaalameda.com/","hours":[[[9.5,13.5],[16,21.5]],[],[[16,21.5]],[[16,21.5]],[[16,21.5]],[[16,22.5]],[[9.5,13.5],[16,22.5]]],"menu":[{"sec":"Tacos","items":[{"n":"Birria Taco","d":"Oxtail and short-rib birria, the house signature","p":"$6.50"},{"n":"Carnitas Taco","d":"Their father's recipe","p":"$6"},{"n":"Carne Asada Taco","d":"Made with 14-oz ribeye","p":"$7"},{"n":"All Seven Signature Tacos","d":"The full lineup for the table","p":"$32"}]},{"sec":"Platos","items":[{"n":"Pork Belly en Salsa Verde","d":"Smothered in bright salsa verde","p":"$24"},{"n":"Whole Branzino","d":"Achiote, garlic and citrus marinade","p":"$34"},{"n":"Weekend Brunch","d":"Breakfast-meets-lunch menu, Sat & Sun morning","p":"$14+"}]}]},
  {"name":"Southie","cuisine":"American","featured":false,"img":"","rating":"4.2","price":"$","tags":["Sandwiches","Craft Beer","Casual","Park Station"],"cats":["delivery"],"desc":"The beloved East Bay sandwich shop's Alameda outpost at the foot of Park Street — hearty made-to-order sandwiches and salads alongside Park Station's craft beer. Counter-casual and quick.","address":"1200 Park St, Alameda, CA 94501","phone":"+15106964247","phoneLabel":"(510) 696-4247","website":"https://parkstation.beer/food","menuUrl":"https://www.toasttab.com/local/order/southie-alameda-1200-park-street","reserve":"https://www.toasttab.com/local/order/southie-alameda-1200-park-street","hours":[[[10.5,19]],[[11.5,20]],[[11.5,20]],[[11.5,20]],[[11.5,20]],[[12,21]],[[12,21]]],"menu":[{"sec":"Sandwiches","items":[{"n":"Meatball Sandwich","d":"House meatballs, red sauce, melted cheese","p":"$15"},{"n":"Fried Chicken Sandwich","d":"Crispy thigh, slaw, house sauce","p":"$15"},{"n":"The Arnold P","d":"A house signature stack","p":"$15"}]},{"sec":"Sides & Sips","items":[{"n":"Seasonal Salad","d":"Market greens, house dressing","p":"$12"},{"n":"Park Station Draft Beer","d":"Rotating local taps next door","p":"$8"}]}]},
  {"name":"Tahina Fresh Mediterranean","cuisine":"Mediterranean","featured":false,"img":"","rating":"4.4","price":"$","tags":["Falafel","Shawarma","Counter-Serve","Fresh"],"cats":["delivery","vegan"],"desc":"Fast, fresh Mediterranean at the Alameda Marketplace end of Park Street — hand-rolled falafel, chicken shawarma, creamy hummus and loaded pita wraps, with plenty of vegetarian and vegan options.","address":"1650 Park St, Ste F, Alameda, CA 94501","phone":"+15102275457","phoneLabel":"(510) 227-5457","website":"https://tahinafreshmed.com/","menuUrl":"https://tahinafreshmed.com/menu","reserve":"https://tahinafreshmed.com/menu","hours":[[[11,15]],[[11,19.5]],[[11,19.5]],[[11,19.5]],[[11,19.5]],[[11,19.5]],[[11,19]]],"menu":[{"sec":"Wraps & Plates","items":[{"n":"Falafel Pita","d":"Hand-rolled falafel, tahini, pickles, salad","p":"$13"},{"n":"Chicken Shawarma Wrap","d":"Marinated spit chicken, garlic sauce","p":"$14"},{"n":"Shawarma Plate","d":"With rice, salad, hummus and pita","p":"$18"}]},{"sec":"Sides","items":[{"n":"Hummus & Pita","d":"Silky house hummus, warm pita","p":"$8"},{"n":"Mediterranean Salad","d":"Cucumber, tomato, herbs, lemon","p":"$10"},{"n":"Baklava","d":"Honeyed, flaky, nutty","p":"$4"}]}]},
  {"name":"Phnom Penh House","cuisine":"Cambodian","featured":false,"img":"","rating":"4.4","price":"$","tags":["Cambodian","Since 1986","Family-Owned","Webster St"],"cats":[],"desc":"A West End treasure since 1986 — family-owned Cambodian cooking with shareable plates that lean into smoky, salty and sweet: spicy papaya salad, lemongrass tofu, and seafood soups.","address":"1514 Webster St, Alameda, CA 94501","phone":"+15108933825","phoneLabel":"(510) 893-3825","website":"https://www.phnompenhhouse.com/","menuUrl":"https://www.phnompenhhouse.com/","reserve":"https://www.phnompenhhouse.com/","hours":[[],[[11,20.5]],[[11,20.5]],[[11,20.5]],[[11,20.5]],[[11,20.5]],[[11,20.5]]],"menu":[{"sec":"Starters & Salads","items":[{"n":"Spicy Papaya Salad","d":"Bright, fiery green papaya","p":"$14"},{"n":"Sngor Chrourk","d":"Tangy Cambodian seafood soup","p":"$16"}]},{"sec":"Mains","items":[{"n":"Spicy Tofu with Lemongrass","d":"Wok-fired, aromatic, vegetarian","p":"$15"},{"n":"Singapore Noodles","d":"Curried thin noodles, the crowd favorite","p":"$15"},{"n":"Cambodian Curry","d":"House curry with choice of protein","p":"$17"}]}]},
  {"name":"Neptune's","cuisine":"American","featured":false,"img":"","rating":"4.3","price":"$","tags":["Brunch","Filipino-Inspired","Silogs","Coffee"],"cats":["breakfast"],"desc":"Daytime-only brunch spot on Central Ave serving breakfast classics with a Californian-Filipino spin — fried chicken and longanisa silogs over garlic fried rice, stuffed breakfast burritos, and kale benedicts.","address":"630 Central Ave, Alameda, CA 94501","phone":"+15102639438","phoneLabel":"(510) 263-9438","website":"https://www.neptunesalameda.com/","menuUrl":"https://www.neptunesalameda.com/brunch-menu","reserve":"https://www.neptunesalameda.com/","hours":[[[8.5,14.5]],[[8.5,14.5]],[],[[8.5,14.5]],[[8.5,14.5]],[[8.5,14.5]],[[8.5,14.5]]],"menu":[{"sec":"Silogs","items":[{"n":"Fried Chicken Silog","d":"Buttermilk thigh & wing, honey glaze, sunny egg, garlic fried rice, pickled veg","p":"$18"},{"n":"Longanisa Silog","d":"Sweet Filipino sausage, garlic rice, sunny egg","p":"$17"}]},{"sec":"Brunch","items":[{"n":"Breakfast Burrito","d":"Bacon, tater tots, egg and cheese, big enough to share","p":"$15"},{"n":"Kale Benedict","d":"Poached eggs, hollandaise, greens","p":"$16"},{"n":"Joe Coffee Drinks","d":"Espresso bar in-house","p":"$5"}]}]}
];
